.travis.yml: Remove 9.2 because it raises a warning
For 9.2, there is a compiler warning:

utils.c: In function ‘parse_default_version_in_control_file’:
utils.c:87:35: error: ‘/extension/’ directive output may be truncated writing 11 bytes into a region of size between 1 and 1024 [-Werror=format-truncation=]
   87 |  snprintf(filename, MAXPGPATH, "%s/extension/%s.control", sharepath, extname);
      |                                   ^~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /usr/include/postgresql/9.2/server/c.h:67,
                 from /usr/include/postgresql/9.2/server/postgres.h:47,
                 from utils.c:22:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: [K‘__builtin___snprintf_chk’ output 20 or more bytes (assuming 1043) into a destination of size 1024
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

As the newer versions are fine, and 9.2 is well EOL, remove it from the
list of versions to be tested.